In [33]:
import numpy as np


def DNN(X,y,epoch,lr):
  np.random.seed(142)
  numberOfLayer = 1
  w_input_hidden = np.random.uniform(size=[len(X[0]),3])
  w_hidden = np.random.uniform(size=[5,3,3])
  w_hidden_output = np.random.uniform(size=[3,1])

  def relu(x):
    return np.maximum(0, x)
  def der_relu(x):
      return np.where(x > 0, 1, 0)
  
  def sigmoid(x):
    return 1 / (1 + np.exp(-x))
  def der_sigmoid(x):
    return sigmoid(x) * (1- sigmoid(x))
  
  output = []
  for j in range(len(X)):
    for i in range(epoch):

      summation_array = []

      z = np.dot(X[j],w_input_hidden)
      a1 = sigmoid(z)
      summation_array.append(z)

      for i in range(numberOfLayer):
        z = np.dot(a1,w_hidden[i])
        a1 = sigmoid(z)
        summation_array.append(z)

      z = np.dot(a1,w_hidden_output)
      a3 = sigmoid(z)

      error_output = y[j] - a3
      delta_output = error_output * der_sigmoid(a3)

      delta_hidden = []
      for i in range(numberOfLayer-1,-1,-1):
          if i==numberOfLayer-1:
              error_hidden = delta_output.dot(w_hidden_output.T)
              delta_hidden.append(error_hidden * der_sigmoid(summation_array[i]))

          else : 
              error_hidden = delta_hidden[-1].dot(w_hidden[i+1])
              delta_hidden.append(error_hidden * der_sigmoid(summation_array[i]))
      error_hidden = delta_hidden[-1].dot(w_hidden[0].T)
      delta_input_hidden = error_hidden*der_sigmoid(summation_array[0])

      w_input_hidden += delta_input_hidden * lr

      for i in range(numberOfLayer-1,-1,-1):
        w_hidden[i] += delta_hidden[i] * lr

      w_hidden_output += delta_output * lr
    output.append(a3)
  
  return output


X = np.array([[0,0],[1,0],[0,1],[1,1]])
y = [0,1,1,0]

pred = DNN(X,y,epoch=100,lr=0.5)
pred

[array([0.03717647]),
 array([0.95275179]),
 array([0.97884798]),
 array([0.03990536])]

In [34]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
X,y = load_digits().data,[1 if i == 3 else 0 for i in load_digits().target]
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=0.2)

In [28]:
pred = DNN(xtrain,ytrain,epoch=200,lr=0.3)